services:
  database:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
  spring-app:
    container_name: ${APP_CONTAINER_NAME}
    build: .
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:postgresql://${DB_CONTAINER_NAME}:5432/${DB_NAME}
      - spring.datasource.username=${DB_USER}
      - spring.datasource.password=${DB_PASS}
      - spring.profiles.active=docker

