spring:
  jpa:
    hibernate:
      ddl-auto: validate
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs/ui
---
spring:
  datasource:
    url: jdbc:h2:mem:dev
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    activate:
      on-profile: development
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    driver-class-name: org.postgresql.Driver
    platform: postgres
